import os
from getpass import getpass
from urllib.request import urlopen
import json
import textwrap
from elasticsearch import Elasticsearch
from sentence_transformers import SentenceTransformer


# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.environ.get('ELASTIC_PASSWORD')

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="", #/home/iv.kem/http_ca.crt Example
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}

folder_path = "test_files/"  # Replace with the actual folder path

# Define the mapping
mappings = {
    "properties": {
        "language": {"type": "keyword"},
        "id": {"type": "keyword"},
        "title": {"type": "text"},
        "passage": {"type": "text"},
        "passage_embedding": {
            "type": "dense_vector",
            "dims": 768,
            "index": "true",
            "similarity": "cosine"
        }
    }
}

# Create the index (deleting any previously existing index)
client.indices.delete(index="articles", ignore_unavailable=True)
client.indices.create(index="articles", mappings=mappings)
